services:

  node-monitor:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - mongodb

  mongodb:
    image: mongo:4.4
    volumes:
      - mongodb_data:/data/db