fastapi:
  host: 0.0.0.0
  port: 5010
scanner:
  scan_interval: 300  # интервал сканирования в секундах
  timeout: 5          # таймаут подключения
  rpc_port: 38081     # порт RPC API

mongodb:
  uri: mongodb://mongodb.localhost:27017
  database: pocketnet_monitor

initial_peers:
  - "1.pocketnet.app"
  - "2.pocketnet.app"

logging:
  level: info  # или debug, info, warning, error, critical