fastapi:
  host: 0.0.0.0
  port: 5000

scanner:
  scan_interval: 300  # интервал сканирования в секундах
  timeout: 5          # таймаут подключения
  rpc_port: 38081     # порт RPC API

mongodb:
  uri: mongodb://172.19.0.3:27017
  database: pocketnet_monitor

initial_peers:
  - "1.pocketnet.app"
  - "2.pocketnet.app"